### ISSUE TITLE
Merge pull request #6 from 100suping/streamlit 수정이 필요한 사항

### ISSUE THREAD

**Issue by pakyeon** [100suping/sql-helper#9]
## 어떤 버그인가요?
15번 `llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)` 현재 gpt-3.5-turbo를 사용하고 있습니다. 
21번 `chain = create_sql_query_chain(llm, db)` 은 사용되고 있지 않습니다.
## 어떤 상황에서 발생한 버그인가요?
15번
- qpt-4o 또는 gpt-4o-mini 로 변경하는 것을 권장합니다.
- 4o : $2.50, 4o-mini: $0.150, 3.5-turbo: $3.000
21번
- 사용되고 있지 않은 코드
## 예상 결과
15번에 경우에는 비용과 성능 때문에 수정이 필요하고
21번에 경우에는 사용되지 않는 코드라서 필요에 따라 수정하시면 됩니다.

**Comment by cho1133** [comment]
한번 확인해보겠습니다.

**Comment by cho1133** [comment]
새롭게 pr 했습니다.
